/**
 * HTML reporter.
 *
 * Renders the evidence store into a self-contained, theme-aware findings
 * dashboard. The design follows shadcn/ui principles: a neutral palette driven
 * by CSS variables, light/dark theming, cards with subtle borders, muted
 * secondary text, and semantic badges. No external assets (inline CSS + a tiny
 * theme toggle), so the file opens or serves anywhere.
 *
 * It keeps Prism's core distinction intact: observed findings and hypotheses
 * live in separate sections and are never mixed.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Evidence, EvidenceStore } from '../evidence/store.js';
import type { ReportMeta } from './markdown.js';
import { summaryParagraph } from './markdown.js';

/** Render the findings dashboard as a self-contained HTML document. */
export function renderHtmlReport(store: EvidenceStore, meta: ReportMeta): string {
  const observed = store.observed();
  const hypothesized = store.hypothesized();

  const confirmed = observed.filter((e) => {
    const v = (e.data as { verdict?: string } | undefined)?.verdict;
    return v === 'confirmed' || v === 'access-controlled';
  }).length;
  const blocked = observed.filter((e) => e.category === 'scope-violation').length;

  const stats = [
    { label: 'Findings', value: store.count() },
    { label: 'Observed', value: observed.length },
    { label: 'Hypotheses', value: hypothesized.length },
    { label: 'Verified', value: confirmed },
    { label: 'Blocked', value: blocked },
  ];

  return `<!doctype html>
<html lang="en" data-theme="">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Prism report — ${escapeHtml(meta.target)}</title>
<style>${STYLES}</style>
</head>
<body>
<div class="wrap">
  <header class="topbar">
    <div class="brand">
      ${PRISM_MARK}
      <div>
        <div class="brand-name">Prism</div>
        <div class="brand-sub">findings report</div>
      </div>
    </div>
    <button id="theme-toggle" class="btn-icon" aria-label="Toggle theme" title="Toggle theme">
      ${SUN_ICON}${MOON_ICON}
    </button>
  </header>

  <section class="meta">
    ${metaItem('Target', `<span class="mono">${escapeHtml(meta.target)}</span>`)}
    ${metaItem('Started', escapeHtml(meta.startedAt))}
    ${metaItem('Finished', escapeHtml(meta.finishedAt))}
    ${meta.concurrency !== undefined ? metaItem('Parallel agents', String(meta.concurrency)) : ''}
    ${
      meta.allowlistSignature !== undefined
        ? metaItem(
            'Allowlist signature',
            `<span class="mono sig">${escapeHtml(meta.allowlistSignature)}</span>`,
          )
        : ''
    }
  </section>

  <section class="stats">
    ${stats.map((s) => statTile(s.label, s.value)).join('\n')}
  </section>

  <section class="card summary">
    <div class="card-head"><h2>Summary</h2></div>
    <div class="card-body">
      <p>${escapeHtml(summaryParagraph(store, meta))}</p>
      <p class="note">Automated recon for authorized testing only. Observed findings were directly seen and can be
      treated as fact. Hypotheses were inferred and must be verified before you rely on them. This run performed no
      exploitation.</p>
    </div>
  </section>

  <div class="section-label"><span class="dot dot-observed"></span> Observed findings <span class="muted">· facts</span></div>
  ${observed.length === 0 ? emptyCard('Nothing observed.') : groupByCategory(observed)}

  <div class="section-label"><span class="dot dot-hypo"></span> Hypotheses <span class="muted">· to investigate, unverified</span></div>
  ${hypothesized.length === 0 ? emptyCard('No hypotheses.') : groupByCategory(hypothesized)}

  <footer class="footer">Generated by Prism · Authorized-scope security research only.</footer>
</div>
<script>${SCRIPT}</script>
</body>
</html>
`;
}

/**
 * Render and write the dashboard to `reports/{target-slug}-{date}.html`.
 * Returns the path written.
 */
export function writeHtmlReport(
  store: EvidenceStore,
  meta: ReportMeta,
  baseDir: string = process.cwd(),
): string {
  const html = renderHtmlReport(store, meta);
  const dir = join(baseDir, 'reports');
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${slugifyTarget(meta.target)}-${dateStamp(meta.finishedAt)}.html`);
  writeFileSync(file, html, 'utf8');
  return file;
}

/** Render each category as a card with a findings table. */
function groupByCategory(evidence: Evidence[]): string {
  const categories = [...new Set(evidence.map((e) => e.category))];
  return categories
    .map((category) => {
      const rows = evidence.filter((e) => e.category === category);
      return `<section class="card">
  <div class="card-head">
    <h3>${escapeHtml(titleCase(category))}</h3>
    <span class="badge badge-muted">${rows.length}</span>
  </div>
  <div class="card-body table-body">
    <table>
      <thead><tr><th>ID</th><th>Finding</th><th>Status</th><th>Severity</th><th>Detail</th></tr></thead>
      <tbody>
        ${rows.map(rowHtml).join('\n')}
      </tbody>
    </table>
  </div>
</section>`;
    })
    .join('\n');
}

function rowHtml(e: Evidence): string {
  const verdict = (e.data as { verdict?: string } | undefined)?.verdict;
  return `<tr>
  <td class="mono id">${escapeHtml(e.id)}</td>
  <td class="finding">${escapeHtml(e.title)}${verdict !== undefined ? ` ${verdictBadge(verdict)}` : ''}</td>
  <td>${e.status !== undefined ? statusBadge(e.status) : ''}</td>
  <td>${e.severity !== undefined ? severityBadge(e.severity) : ''}</td>
  <td class="muted detail">${escapeHtml(e.detail ?? '')}</td>
</tr>`;
}

function statTile(label: string, value: number): string {
  return `<div class="tile"><div class="tile-value">${value}</div><div class="tile-label">${escapeHtml(label)}</div></div>`;
}

function metaItem(label: string, valueHtml: string): string {
  return `<div class="meta-item"><span class="meta-label">${escapeHtml(label)}</span>${valueHtml}</div>`;
}

function emptyCard(text: string): string {
  return `<section class="card"><div class="card-body"><p class="muted">${escapeHtml(text)}</p></div></section>`;
}

function statusBadge(status: number): string {
  const variant = status < 300 ? 'green' : status < 400 ? 'blue' : status < 500 ? 'red' : 'amber';
  return `<span class="badge badge-${variant}">${status}</span>`;
}

function severityBadge(severity: string): string {
  const variant =
    severity === 'high'
      ? 'red'
      : severity === 'medium'
        ? 'amber'
        : severity === 'low'
          ? 'blue'
          : 'muted';
  return `<span class="badge badge-${variant}">${escapeHtml(severity)}</span>`;
}

function verdictBadge(verdict: string): string {
  const map: Record<string, string> = {
    confirmed: 'green',
    'access-controlled': 'amber',
    refuted: 'red',
    'client-route': 'blue',
    inconclusive: 'muted',
  };
  return `<span class="badge badge-${map[verdict] ?? 'muted'}">${escapeHtml(verdict)}</span>`;
}

function titleCase(value: string): string {
  return value
    .split('-')
    .map((word) => (word.length > 0 ? word[0]!.toUpperCase() + word.slice(1) : word))
    .join(' ');
}

function slugifyTarget(target: string): string {
  let host = target;
  try {
    host = new URL(target).host;
  } catch {
    // fall through with the raw string
  }
  const slug = host
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug !== '' ? slug : 'target';
}

function dateStamp(iso: string): string {
  const datePart = iso.split('T')[0];
  return datePart !== undefined && datePart !== '' ? datePart : 'undated';
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const PRISM_MARK =
  '<svg class="mark" width="26" height="26" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3 3 19h18L12 3Z" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round"/><path d="M12 3v16" stroke="currentColor" stroke-width="1.2" opacity="0.5"/><path d="M12 11 3 19M12 11l9 8" stroke="currentColor" stroke-width="1.2" opacity="0.5"/></svg>';

const SUN_ICON =
  '<svg class="i-sun" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>';

const MOON_ICON =
  '<svg class="i-moon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8Z"/></svg>';

const STYLES = `
:root{
  --background:0 0% 100%; --foreground:240 10% 3.9%;
  --card:0 0% 100%; --card-foreground:240 10% 3.9%;
  --muted:240 4.8% 95.9%; --muted-foreground:240 3.8% 46.1%;
  --border:240 5.9% 90%; --primary:240 5.9% 10%;
  --green:142 71% 40%; --red:0 72% 48%; --amber:35 92% 42%; --blue:217 91% 52%;
  --radius:0.6rem;
}
:root[data-theme="dark"]{
  --background:240 10% 3.9%; --foreground:0 0% 98%;
  --card:240 10% 5.5%; --card-foreground:0 0% 98%;
  --muted:240 3.7% 15.9%; --muted-foreground:240 5% 64.9%;
  --border:240 3.7% 17%; --primary:0 0% 98%;
  --green:142 65% 55%; --red:0 84% 68%; --amber:38 95% 62%; --blue:213 93% 68%;
}
@media (prefers-color-scheme: dark){
  :root:not([data-theme="light"]){
    --background:240 10% 3.9%; --foreground:0 0% 98%;
    --card:240 10% 5.5%; --card-foreground:0 0% 98%;
    --muted:240 3.7% 15.9%; --muted-foreground:240 5% 64.9%;
    --border:240 3.7% 17%; --primary:0 0% 98%;
    --green:142 65% 55%; --red:0 84% 68%; --amber:38 95% 62%; --blue:213 93% 68%;
  }
}
*{box-sizing:border-box}
html,body{margin:0}
body{
  background:hsl(var(--background)); color:hsl(var(--foreground));
  font-family:ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;
  font-size:14px; line-height:1.5; -webkit-font-smoothing:antialiased;
}
.wrap{max-width:1040px; margin:0 auto; padding:32px 24px 64px}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
.muted{color:hsl(var(--muted-foreground))}

.topbar{display:flex; align-items:center; justify-content:space-between; margin-bottom:28px}
.brand{display:flex; align-items:center; gap:12px}
.mark{color:hsl(var(--foreground))}
.brand-name{font-weight:600; font-size:18px; letter-spacing:-0.01em}
.brand-sub{color:hsl(var(--muted-foreground)); font-size:12.5px; margin-top:-2px}
.btn-icon{
  display:inline-grid; place-items:center; width:36px; height:36px; cursor:pointer;
  background:hsl(var(--card)); color:hsl(var(--foreground));
  border:1px solid hsl(var(--border)); border-radius:calc(var(--radius) - 2px);
  transition:background .15s ease,border-color .15s ease;
}
.btn-icon:hover{background:hsl(var(--muted))}
.i-moon{display:none} :root[data-theme="dark"] .i-sun{display:none} :root[data-theme="dark"] .i-moon{display:block}
@media (prefers-color-scheme: dark){ :root:not([data-theme="light"]) .i-sun{display:none} :root:not([data-theme="light"]) .i-moon{display:block} }

.meta{
  display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:1px;
  background:hsl(var(--border)); border:1px solid hsl(var(--border));
  border-radius:var(--radius); overflow:hidden; margin-bottom:20px;
}
.meta-item{background:hsl(var(--card)); padding:12px 14px; display:flex; flex-direction:column; gap:3px; min-width:0}
.meta-label{font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:hsl(var(--muted-foreground))}
.meta-item .mono{font-size:12.5px}
.sig{overflow:hidden; text-overflow:ellipsis; white-space:nowrap; display:block}

.stats{display:grid; grid-template-columns:repeat(5,1fr); gap:12px; margin-bottom:24px}
.tile{background:hsl(var(--card)); border:1px solid hsl(var(--border)); border-radius:var(--radius); padding:16px}
.tile-value{font-size:26px; font-weight:650; letter-spacing:-0.02em}
.tile-label{font-size:12px; color:hsl(var(--muted-foreground)); margin-top:2px}
@media (max-width:720px){ .stats{grid-template-columns:repeat(2,1fr)} }

.card{background:hsl(var(--card)); border:1px solid hsl(var(--border)); border-radius:var(--radius); margin-bottom:16px; overflow:hidden}
.card-head{display:flex; align-items:center; gap:10px; padding:14px 18px; border-bottom:1px solid hsl(var(--border))}
.card-head h2,.card-head h3{margin:0; font-size:14.5px; font-weight:600; letter-spacing:-0.01em}
.card-body{padding:16px 18px}
.summary p{margin:0 0 10px} .summary p:last-child{margin-bottom:0}
.note{font-size:12.5px; color:hsl(var(--muted-foreground))}

.section-label{display:flex; align-items:center; gap:8px; font-size:12px; font-weight:600;
  text-transform:uppercase; letter-spacing:.05em; color:hsl(var(--muted-foreground)); margin:28px 2px 12px}
.section-label .muted{text-transform:none; letter-spacing:0; font-weight:400}
.dot{width:8px; height:8px; border-radius:999px}
.dot-observed{background:hsl(var(--green))}
.dot-hypo{background:hsl(var(--amber))}

.table-body{padding:0}
table{width:100%; border-collapse:collapse}
th,td{text-align:left; padding:10px 14px; border-bottom:1px solid hsl(var(--border)); vertical-align:top}
th{font-size:11px; text-transform:uppercase; letter-spacing:.04em; color:hsl(var(--muted-foreground)); font-weight:500}
tbody tr:last-child td{border-bottom:none}
tbody tr:hover{background:hsl(var(--muted) / .5)}
td.id{color:hsl(var(--muted-foreground)); white-space:nowrap; font-size:12.5px}
td.finding{font-weight:500; min-width:220px}
td.detail{font-size:13px; max-width:340px}

.badge{display:inline-flex; align-items:center; gap:4px; font-size:11.5px; font-weight:500; line-height:1;
  padding:3px 8px; border-radius:999px; border:1px solid transparent; white-space:nowrap}
.badge-muted{background:hsl(var(--muted)); color:hsl(var(--muted-foreground)); border-color:hsl(var(--border))}
.badge-green{background:hsl(var(--green) / .13); color:hsl(var(--green)); border-color:hsl(var(--green) / .28)}
.badge-red{background:hsl(var(--red) / .13); color:hsl(var(--red)); border-color:hsl(var(--red) / .28)}
.badge-amber{background:hsl(var(--amber) / .14); color:hsl(var(--amber)); border-color:hsl(var(--amber) / .30)}
.badge-blue{background:hsl(var(--blue) / .13); color:hsl(var(--blue)); border-color:hsl(var(--blue) / .28)}

.footer{margin-top:36px; padding-top:16px; border-top:1px solid hsl(var(--border));
  font-size:12.5px; color:hsl(var(--muted-foreground)); text-align:center}
`;

const SCRIPT = `
(function(){
  var root=document.documentElement, key='prism-theme';
  var saved=null; try{saved=localStorage.getItem(key)}catch(e){}
  if(saved){root.setAttribute('data-theme',saved)}
  document.getElementById('theme-toggle').addEventListener('click',function(){
    var dark=root.getAttribute('data-theme')==='dark'
      || (root.getAttribute('data-theme')!=='light' && matchMedia('(prefers-color-scheme: dark)').matches);
    var next=dark?'light':'dark';
    root.setAttribute('data-theme',next);
    try{localStorage.setItem(key,next)}catch(e){}
  });
})();
`;
