/**
 * Markdown reporter.
 *
 * Renders an {@link EvidenceStore} into a findings report that keeps Prism's
 * central distinction intact: an "Observed findings" section the reader can trust
 * as fact, and a separate "Hypotheses" section of leads to investigate. The two
 * are never mixed.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { Evidence, EvidenceStore } from '../evidence/store.js';

/** Run metadata rendered into the report header. */
export interface ReportMeta {
  /** The target the run was pointed at. */
  target: string;
  /** ISO timestamp the run started. */
  startedAt: string;
  /** ISO timestamp the run finished. */
  finishedAt: string;
  /** Optional allowlist signature, for provenance. */
  allowlistSignature?: string;
  /** Optional number of parallel agents used, for the summary. */
  concurrency?: number;
}

/** Render the full findings report as a Markdown string. */
export function renderMarkdownReport(store: EvidenceStore, meta: ReportMeta): string {
  const observed = store.observed();
  const hypothesized = store.hypothesized();

  const lines: string[] = [];

  lines.push('# Prism findings report');
  lines.push('');
  lines.push(`- **Target:** ${meta.target}`);
  lines.push(`- **Started:** ${meta.startedAt}`);
  lines.push(`- **Finished:** ${meta.finishedAt}`);
  if (meta.concurrency !== undefined) {
    lines.push(`- **Parallel agents:** ${meta.concurrency}`);
  }
  if (meta.allowlistSignature !== undefined) {
    lines.push(`- **Allowlist signature:** \`${meta.allowlistSignature}\``);
  }
  lines.push(
    `- **Findings:** ${store.count()} total, ${observed.length} observed, ${hypothesized.length} hypothesized`,
  );
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(summaryParagraph(store, meta));
  lines.push('');
  lines.push(
    '> Automated recon for authorized testing only. "Observed findings" were directly seen during ' +
      'the run and can be treated as fact. "Hypotheses" were inferred (e.g. paths named in robots.txt) ' +
      'and must be verified before you rely on them. This run performed no exploitation.',
  );
  lines.push('');

  lines.push('## Observed findings (facts)');
  lines.push('');
  if (observed.length === 0) {
    lines.push('_Nothing observed._');
    lines.push('');
  } else {
    renderGroupedByCategory(lines, observed);
  }

  lines.push('## Hypotheses (to investigate — unverified)');
  lines.push('');
  if (hypothesized.length === 0) {
    lines.push('_No hypotheses._');
    lines.push('');
  } else {
    renderGroupedByCategory(lines, hypothesized);
  }

  lines.push('---');
  lines.push('');
  lines.push('_Generated by Prism. Authorized-scope security research only._');
  lines.push('');

  return lines.join('\n');
}

/**
 * Render the report and write it to `reports/{target-slug}-{date}.md`, creating
 * the directory if needed. Returns the path written.
 */
export function writeMarkdownReport(
  store: EvidenceStore,
  meta: ReportMeta,
  baseDir: string = process.cwd(),
): string {
  const report = renderMarkdownReport(store, meta);
  const dir = join(baseDir, 'reports');
  mkdirSync(dir, { recursive: true });
  const file = join(dir, `${slugifyTarget(meta.target)}-${dateStamp(meta.finishedAt)}.md`);
  writeFileSync(file, report, 'utf8');
  return file;
}

/** One-paragraph plain-language summary of the run. Shared with the HTML reporter. */
export function summaryParagraph(store: EvidenceStore, meta: ReportMeta): string {
  const observed = store.observed();
  const hypothesized = store.hypothesized();
  const agents =
    meta.concurrency !== undefined ? `${meta.concurrency} parallel agents` : 'the recon agent';

  const identified = observed.find((e) => e.title.startsWith('Target identified as'));
  const reachable = observed.filter(
    (e) => e.category === 'endpoint' && (e.status ?? 999) < 400,
  ).length;
  const scripts = observed.filter(
    (e) => e.category === 'resource' && e.title.startsWith('Client-side script'),
  ).length;
  const blocked = observed.filter((e) => e.category === 'scope-violation').length;

  const verifications = observed.filter((e) => e.category === 'verification');
  const verdictCount = (verdict: string): number =>
    verifications.filter((e) => (e.data as { verdict?: string } | undefined)?.verdict === verdict)
      .length;

  const parts: string[] = [];
  parts.push(
    `Prism ran ${agents} against ${meta.target} and recorded ${store.count()} findings ` +
      `(${observed.length} observed, ${hypothesized.length} hypothesized).`,
  );
  if (identified !== undefined) {
    parts.push(
      `${identified.title.replace(/^Target identified as /, 'The target was identified as ')}.`,
    );
  }
  parts.push(
    `It found ${reachable} reachable well-known path(s) and ${scripts} client-side script bundle(s), ` +
      `and raised ${hypothesized.length} hypothesized lead(s).`,
  );
  if (verifications.length > 0) {
    parts.push(
      `The verify agent checked ${verifications.length} of them: ` +
        `${verdictCount('confirmed') + verdictCount('access-controlled')} confirmed, ` +
        `${verdictCount('refuted')} refuted, ${verdictCount('client-route')} client-side route(s).`,
    );
  }
  if (blocked > 0) {
    parts.push(`${blocked} out-of-scope request(s) were blocked by the scope-guard.`);
  }
  return parts.join(' ');
}

/** Render a set of evidence grouped into a table per category. */
function renderGroupedByCategory(lines: string[], evidence: Evidence[]): void {
  const categories = [...new Set(evidence.map((e) => e.category))];
  for (const category of categories) {
    const rows = evidence.filter((e) => e.category === category);
    lines.push(`### ${titleCase(category)} (${rows.length})`);
    lines.push('');
    lines.push('| ID | Finding | Status | Sev | Detail |');
    lines.push('| --- | --- | --- | --- | --- |');
    for (const e of rows) {
      lines.push(
        `| ${e.id} | ${escapeCell(e.title)} | ${e.status ?? ''} | ${e.severity ?? ''} | ${escapeCell(e.detail ?? '')} |`,
      );
    }
    lines.push('');
  }
}

/** `http://localhost:3000` -> `localhost-3000`. */
function slugifyTarget(target: string): string {
  let host = target;
  try {
    host = new URL(target).host;
  } catch {
    // fall through with the raw string
  }
  const slug = host
    .replace(/[^a-zA-Z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .toLowerCase();
  return slug !== '' ? slug : 'target';
}

/** ISO timestamp -> `YYYY-MM-DD`. */
function dateStamp(iso: string): string {
  const datePart = iso.split('T')[0];
  return datePart !== undefined && datePart !== '' ? datePart : 'undated';
}

/** "scope-violation" -> "Scope Violation". */
function titleCase(value: string): string {
  return value
    .split('-')
    .map((word) => (word.length > 0 ? word[0]!.toUpperCase() + word.slice(1) : word))
    .join(' ');
}

/** Escape a value for use inside a Markdown table cell. */
function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, ' ');
}
